Refactoring/nico
bojkomatias/uap-vid pull request #205
Opened 2023-09-18 07:57 UTC by nicohorn

Refactored some components and added some documentation. Project is now slightly cleaner.

2023-09-19 15:35 UTC, bojkomatias commented on src/modules/academic-unit/academic-unit-budget-update.tsx
> +                priceSetter={(price: number) => setNewAmount(price)}
priceSetter function already specifies in component (value:number) => void, hence type is already infered

2023-09-19 15:46 UTC, bojkomatias requested changes
Good documentation overall

Suggestions remove unnecessary typings, already inferred

2023-09-19 15:46 UTC, bojkomatias commented on src/modules/elements/popover.tsx
> +                        `${buttonStyle('secondary', false)} px-2 py-1 text-xs`
```suggestion
                        buttonStyle('secondary', false), 'px-2 py-1 text-xs'
```

2023-09-19 15:46 UTC, bojkomatias commented on src/modules/elements/popover.tsx
> +                        `${buttonStyle('secondary', false)} px-2 py-1 text-xs`
buttonStyle returns a string, no need to interpolate, just concatenate

2023-09-19 15:46 UTC, bojkomatias commented on src/modules/protocol/elements/inputs/currency-input.tsx
> +                priceSetter={(price: number) => form.setFieldValue(path, price)}
```suggestion
                priceSetter={(price) => form.setFieldValue(path, price)}
```

2023-09-19 15:46 UTC, bojkomatias commented on src/modules/elements/popover.tsx
>                                  onClick={async () => {
```suggestion
                                onClick={() => {
```

2023-09-19 15:46 UTC, bojkomatias commented on src/modules/academic-unit/academic-unit-budget-update.tsx
> +                priceSetter={(price: number) => setNewAmount(price)}
```suggestion
                priceSetter={(price) => setNewAmount(price)}
```

2023-09-19 17:27 UTC, nicohorn commented on src/modules/protocol/elements/inputs/currency-input.tsx
> +                priceSetter={(price: number) => form.setFieldValue(path, price)}
![image](https://github.com/bojkomatias/uap-vid/assets/50425596/d4efc649-de8b-4512-b70f-58802e8a3fa5)

2023-09-19 17:30 UTC, nicohorn commented on src/modules/academic-unit/academic-unit-budget-update.tsx
> +                priceSetter={(price: number) => setNewAmount(price)}
Same as with my previous comment

2023-09-21 17:29 UTC, bojkomatias commented on src/modules/protocol/elements/inputs/currency-input.tsx
> +                priceSetter={(price: number) => form.setFieldValue(path, price)}
Epa epa, que rarooo!

2023-09-21 17:31 UTC, bojkomatias commented on src/modules/protocol/elements/inputs/currency-input.tsx
> +                priceSetter={(price: number) => form.setFieldValue(path, price)}
<img width="402" alt="Screen Shot 2023-09-21 at 14 30 33" src="https://github.com/bojkomatias/uap-vid/assets/55543631/b7b9c098-b846-4c93-a137-30c9b7e20acc">

Tenés esto así? Porque no estaría funcionando la inference

2023-09-21 17:33 UTC, bojkomatias approved these changes
Inference not working on Nico's PC, not a big deal anyways

2023-09-21 17:33 UTC, merged