Hotfix/UI change budget modal
bojkomatias/uap-vid pull request #237
Opened 2023-10-25 01:29 UTC by nicohorn

A few improvements to UI elements related to the budget generation.

2023-10-25 03:42 UTC, amilcarrey requested changes

2023-10-25 03:42 UTC, amilcarrey commented on src/modules/protocol/elements/action-buttons/generate-anual-budget.tsx
> +            {!hasBudgetCurrentYear ? (
Si se está validando si se tiene presupuesto o no, no debería negarse al pasar la variable como prop a este componente? Me parece que semanticamente acá queda confuso.

2023-10-25 03:42 UTC, amilcarrey commented on src/modules/protocol/elements/action-buttons/generate-anual-budget.tsx
>                      Generar presupuesto
Esto está funcionando joya, es decir crea el presupuesto, pero no triggerea la notificación ni se cierra el modal. Probé con este protocolo https://uap-vid-git-feature-pq-227-asignar-team-memb-894d3a-bojkomatias.vercel.app/protocols/64caba1a440559cf1c665984. 

Creo que un router.refresh() con el useTransition podría solucionar el problem, ya que si ahora entras en el protocolo no te permite generar nuevo presupuesto, pero si vas a la lista de presupuesto hay 6 (los que cree yo porque creia que no funcaba el boton jaja)

2023-10-25 03:48 UTC, nicohorn commented on src/modules/protocol/elements/action-buttons/generate-anual-budget.tsx
> +            {!hasBudgetCurrentYear ? (
Estoy en esto, la idea es validarlo en la server action. Esto no sería una validación en sí, sino una mejora en la experiencia de usuario porque muestra el botón en disabled para que el usuario entienda por qué no puede crear el budget.

2023-10-25 04:01 UTC, nicohorn commented on src/modules/protocol/elements/action-buttons/generate-anual-budget.tsx
>                      Generar presupuesto
Sí, estoy con esto también. Hice la PR porque quería separar la UI de la parte lógica.

2023-10-25 04:02 UTC, nicohorn commented on src/modules/protocol/elements/action-buttons/generate-anual-budget.tsx
>                      Generar presupuesto
Digo esto porque creo, no estoy seguro, de que el problema no es de UI si no de lógica.

2023-10-29 07:38 UTC, nicohorn commented
Fully finished now

2023-10-30 11:55 UTC, amilcarrey approved these changes

2023-10-31 17:22 UTC, merged