Feature/pq 122 create convocatory panel
bojkomatias/uap-vid pull request #84
Opened 2023-04-04 23:04 UTC by bojkomatias

Cree el panel de convocatorias.

- pagina con tabla que lista convocatorias
- pagina dinamica con formulario, donde se crea/edita una convocatoria
- cree los metodos correspondientes en el repositorio
- agregue nuevas rutas para POST y PUT :id

```
TODO: Preguntar si se pueden crear 2 convocatorias en mismo timespan
TODO: Maybe standarize all dates from "Intl"
```

2023-04-04 23:48 UTC, amilcarrey requested changes
Como siempre muy bien, pero te requestee un par de cambiecitos. Validaciones en el form y capaz utlizar otros tipos de input. 

Por otro lado, al menos en la versión de preview, no me está guardando. Tira el 200 y aparece el toast como que todo ok, pero en la pestaña de network no sale ningun post. El put no lo pude probar porque no puedo crear nignuno.

2023-04-04 23:48 UTC, amilcarrey commented on src/utils/zod/index.ts
> +    year: z.number(),
El año debeeria ser no mayor al año actual + 1. Las convocatorias se abren con un año de anticipación.

2023-04-04 23:48 UTC, amilcarrey commented on src/modules/auth/navigation.tsx
> +                    No existe una convocatoria activa
Esto podríamos directamente sacarlo. Es decir, un ? CurrentConvocatoru : null. En el boton de crear protocolo lo veo mas conveniente. 

En cualquier caso, solo ocurriría los primeros 10 minutos después del deploy, luego siempre habrán convocatorias o me equivoco?

2023-04-04 23:48 UTC, amilcarrey commented on src/modules/convocatory/convocatory-form.tsx
> +                <input
Este input y el de abajo, te parece que podríamos utilizar el DatePicker de mantine?

2023-04-04 23:48 UTC, amilcarrey commented on src/utils/zod/index.ts
>      to: z.coerce.date(),
To  debe ser mayor a from

2023-04-04 23:48 UTC, amilcarrey commented on src/utils/zod/index.ts
> +    year: z.number(),
`
 year: z
                    .number({
                        invalid_type_error: 'Este campo debe ser numérico',
                    })
                    .max(new Date().getFullYear() + 1, {
                        message: 'No puede ser mayor al año actual',
                    }),
`
Algo así similar al de bibliography

2023-04-05 00:02 UTC, bojkomatias commented on src/utils/zod/index.ts
> +    year: z.number(),
Me parece excelente! Dejemos que sea inclusive hasta el año actual, por si se les pasa la tortuga.

2023-04-05 00:03 UTC, bojkomatias commented on src/modules/auth/navigation.tsx
> +                    No existe una convocatoria activa
Y en teoria no, porque este timer solo apunta a la CurrentConvocatory, pero puede quedar :null si

2023-04-05 03:17 UTC, amilcarrey approved these changes
Te deje dos comentarios mas pero son triviales. Aprobado maquinola

2023-04-05 03:21 UTC, bojkomatias commented on src/repositories/convocatory.ts
>          return await prisma.convocatory.findFirst({
Mañana preguntamos si existen superpuestas, ojala no jaja

2023-04-05 03:22 UTC, merged